server:
  servlet:
    context-path: /
  port: 6633
spring:
  application:
      name: microservices-cloud-gateway-api-project
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:9928
    activate:
      on-profile: default
  cloud:
      config:
          fail-fast: false
          retry:
              initial-interval: 1000
              max-interval: 2000
              multiplier: 1.5
              max-attempts: 6 
      gateway:
          routes:
            -   id: microservices-product-service-project
                predicates:
                - Path=/api/product/**
                uri: lb://microservices-product-service-project
            -   id: microservices-payment-service-project
                predicates:
                - Path=/api/payment/**
                uri: lb://microservices-payment-service-project
            -   id: microservices-order-service-project
                predicates:
                - Path=/api/order/**
                uri: lb://microservices-order-service-project
  security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:1030/realms/microservices_master_realm/protocol/openid-connect/certs
management:
    tracing:
        sampling:
            probability: 1.0